### ISSUE TITLE
Pressing backspace erases two digits at once

### ISSUE THREAD

**Issue by luistrivelatto** [gtgalone/currency_text_input_formatter#11]
I'm experiencing an issue where this happens:
1. Create TextField with `keyboardType: TextInputType.number` or `TextInputType.numberWithOptions` (for the default keyboardType, it works normally)
2. TextField = "123.45"
3. Press backspace on the Android keyboard
4. TextField = "1.23" (expected: "12.34")

It seems this is due to Flutter's framework calling `formatEditUpdate` twice after a backspace press. Googling a bit, I found this issue which might be related (it was solved, but later rolled back) - the issue also seemed to happen only with the number keyboard: https://github.com/flutter/flutter/issues/48608

I added a log statement to `formatEditUpdate` and noticed that it indeed was being called more than once. Now, this method being called more than once wouldn't be a problem if it weren't for lines 49-52:
```dart
49    String oldText = oldValue.text.replaceAll(RegExp('[^0-9]'), '');
50    if (newText == oldText) {
51      newText = newText.substring(0, newText.length - 1);
52    }
```

From what I've seen, the framework calls (for a single backspace press):
```
formatEditUpdate(oldValue: "123.45", newValue: "123.4") -> returns "12.34"
formatEditUpdate(oldValue: "12.34", newValue: "123.4") -> returns "1.23"
```
In the second call, the if condition is true, and the return value is stripped out of the last digit.

Removing lines 49-52 seem to make it work fine for me (the method still gets called twice, but only a single digit gets erased). However, I imagine there's a reason for those lines to be there in the first place, so before sending a PR, I wanted to ask: what is the logic behind that if condition? Does removing it break some other case?

**Comment by gtgalone** [comment]
@luistrivelatto 

Sorry for late.

I have just tested it, But It works fine.

Could you provide full TextField options?

**Comment by luistrivelatto** [comment]
Sure, here's code which reproduces the bug on my device:
```dart
import 'package:currency_text_input_formatter/currency_text_input_formatter.dart';
import 'package:flutter/material.dart';

void main() {
  runApp(MaterialApp(
    home: Scaffold(
      body: Padding(
        padding: const EdgeInsets.all(20.0),
        child: TextField(
          inputFormatters: [CurrencyTextInputFormatter()],
          keyboardType: TextInputType.number,
        ),
      ),
    ),
  ));
}
```

And here's what happens:
<img src="https://user-images.githubusercontent.com/21317528/102927257-63228080-4475-11eb-93aa-cbb153826d44.gif" width="250"/>

Since this is a bug from the framework (calling the inputFormatter twice for one backspace press), and it's closely related to the device (due to integration with the native keyboard), I suspect this is a bug that happens only on certain devices. Here's my flutter doctor for reference:
```
[√] Flutter (Channel dev, 1.24.0-7.0.pre, on Microsoft Windows [versÃ£o 10.0.18363.1256], locale pt-BR)
    • Flutter version 1.24.0-7.0.pre at C:\src\flutter
    • Framework revision a0860f6e87 (8 weeks ago), 2020-10-29 20:07:34 -0700
    • Engine revision 073263e39d
    • Dart version 2.11.0 (build 2.11.0-260.0.dev)

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.0)
    • Android SDK at C:\Users\Luis\AppData\Local\Android\sdk
    • Platform android-30, build-tools 29.0.0
    • Java binary at: C:\Program Files\Android\Android Studio\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at C:\Program Files (x86)\Google\Chrome\Application\chrome.exe

[√] Android Studio (version 4.1.0)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b01)

[√] Connected device (4 available)
    • SM A530F (mobile) • 32000d27bcf17513 • android-arm64  • Android 9 (API 28)
    • Web Server (web)  • web-server       • web-javascript • Flutter Tools
    • Chrome (web)      • chrome           • web-javascript • Google Chrome 87.0.4280.88
    • Edge (web)        • edge             • web-javascript • Microsoft Edge 87.0.664.52
```

**Comment by gtgalone** [comment]
@luistrivelatto 

Sorry for late. I just woke up.

Okay.

Could you change and test with with this code in your environment?
I cannot make a same environment with you.

from
```dart
49    String oldText = oldValue.text.replaceAll(RegExp('[^0-9]'), '');
50    if (newText == oldText) {
51      newText = newText.substring(0, newText.length - 1);
52    }
```

to

```dart
49    if (newValue.text == oldValue.text) {
50      newText = newText.substring(0, newText.length - 1);
51    }
```

I think we need to check with decimal.

Because '123.4' and '12.34' is different. But now check without decimal like '1234' and '1234'.

after you are check and test with that code, if works fine.

You can make PR.

**Comment by gtgalone** [comment]
@luistrivelatto 

Sorry for late. I just woke up.

Okay.

Could you change and test with with this code in your environment?
I cannot make a same environment with you.

from
```dart
49    String oldText = oldValue.text.replaceAll(RegExp('[^0-9]'), '');
50    if (newText == oldText) {
51      newText = newText.substring(0, newText.length - 1);
52    }
```

to
```dart
49    if (newValue.text == oldValue.text) {
50      newText = newText.substring(0, newText.length - 1);
51    }
```

**Comment by gtgalone** [comment]
@luistrivelatto 

Sorry for late. I just woke up.

Okay.

Could you change and test with with this code in your environment?
I cannot make a same environment with you.

from
```dart
49    String oldText = oldValue.text.replaceAll(RegExp('[^0-9]'), '');
50    if (newText == oldText) {
51      newText = newText.substring(0, newText.length - 1);
52    }
```

to
```dart
49    String newTextWithoutSymbol =
50        newValue.text.replaceAll(RegExp('[^0-9.,]'), '');
51    String oldTextWithoutSymbol =
52        oldValue.text.replaceAll(RegExp('[^0-9.,]'), '');
53    if (newTextWithoutSymbol == oldTextWithoutSymbol) {
54      newText = newText.substring(0, newText.length - 1);
55    }
```

If works fine, You can make PR with this code.

**Comment by gtgalone** [comment]
@luistrivelatto

Sorry for late. I just woke up.

Okay.

Could you change and test with this code in your environment?
I cannot make a same environment with you.

from

49    String oldText = oldValue.text.replaceAll(RegExp('[^0-9]'), '');
50    if (newText == oldText) {
51      newText = newText.substring(0, newText.length - 1);
52    }
to

49    String newTextWithoutSymbol =
50        newValue.text.replaceAll(RegExp('[^0-9.,]'), '');
51    String oldTextWithoutSymbol =
52        oldValue.text.replaceAll(RegExp('[^0-9.,]'), '');
53    if (newTextWithoutSymbol == oldTextWithoutSymbol) {
54      newText = newText.substring(0, newText.length - 1);
55    }
If works fine, You can make PR with this code.

**Comment by gtgalone** [comment]
@luistrivelatto

Sorry for late. I just woke up.

Okay.

Could you change and test with this code in your environment?
I cannot make a same environment with you.

from

```dart
49 String oldText = oldValue.text.replaceAll(RegExp('[^0-9]'), '');
50 if (newText == oldText) {
51   newText = newText.substring(0, newText.length - 1);
52 }
```
to
```dart
49 String newTextWithoutSymbol =
50   newValue.text.replaceAll(RegExp('[^0-9.,]'), '');
51 String oldTextWithoutSymbol =
52   oldValue.text.replaceAll(RegExp('[^0-9.,]'), '');
53 if (newTextWithoutSymbol == oldTextWithoutSymbol) {
54   newText = newText.substring(0, newText.length - 1);
55 }
```
If works fine, You can make PR with this code.

**Comment by luistrivelatto** [comment]
I will test it, thanks :)

One question though: are those lines needed? If I understood correctly, their purpose is to remove characters added that are not valid characters for currency, right? (e.g. if the user adds an types '1', '2', '3', 'a', the 'a' would get removed). But line 33 already takes care of that:
```dart
33    String newText = newValue.text.replaceAll(RegExp('[^0-9]'), '');
```
Because it removes any non-digit character from the input string. So correct if I'm wrong, if there's another reason for lines 49-52, but I think they can just be erased. I've done that in my project and it seems to be working fine :)

**Comment by gtgalone** [comment]
@luistrivelatto 

Yes. both are needed.

33 line is only for digit processing.

49 line is for ignoring suffix symbol while deleting digit.

**Comment by luistrivelatto** [comment]
Ohh, ok, now I get it, thanks! I wasn't considering suffix symbols, now I understand the purpose of the if-clause.

Your solution works for the case I mentioned on the first post! In fact, I've only found a minor thing with it (that, if there's a suffix symbol, we can never erase the whole input, it always stay as "0.00 $"), but that's not really a problem.

The bad news is that Flutter is being mean to me :( After adding a suffix symbol, I'm now actually seeing logs for 4 (!!) executions of `formatEditUpdate` for a single backspace press. And then it doesn't erase anything at all (it seems the fix for this will need to be some sort of hack to account for the framework bug).

Here's a couple of examples logging the inputs and output after a single backspace press:
```
Using CurrencyTextInputFormatter(): calls formatEditUpdate 2x, code works

I/flutter (23063): oldValue.text = ┤0.12├   newValue.text = ┤0.1├   return = ┤0.01├
I/flutter (23063): oldValue.text = ┤0.01├   newValue.text = ┤0.1├   return = ┤0.01├

I/flutter (23063): oldValue.text = ┤123,456.78├   newValue.text = ┤123,456.7├   return = ┤12,345.67├
I/flutter (23063): oldValue.text = ┤12,345.67├   newValue.text = ┤123,456.7├   return = ┤12,345.67├
```
```
Using CurrencyTextInputFormatter(symbol: '€', locale: 'es'): calls formatEditUpdate 4x, code doesn't erase anything

I/flutter (23063): oldValue.text = ┤0,12 €├   newValue.text = ┤0,12 ├   return = ┤0,01 €├
I/flutter (23063): oldValue.text = ┤0,01 €├   newValue.text = ┤0,12 ├   return = ┤0,12 €├
I/flutter (23063): oldValue.text = ┤0,12 €├   newValue.text = ┤0,01 €├   return = ┤0,01 €├
I/flutter (23063): oldValue.text = ┤0,01 €├   newValue.text = ┤0,12 €├   return = ┤0,12 €├

I/flutter (23063): oldValue.text = ┤123.456,78 €├   newValue.text = ┤123.456,78 ├   return = ┤12.345,67 €├
I/flutter (23063): oldValue.text = ┤12.345,67 €├   newValue.text = ┤123.456,78 ├   return = ┤123.456,78 €├
I/flutter (23063): oldValue.text = ┤123.456,78 €├   newValue.text = ┤12.345,67 €├   return = ┤12.345,67 €├
I/flutter (23063): oldValue.text = ┤12.345,67 €├   newValue.text = ┤123.456,78 €├   return = ┤123.456,78 €├
```

So basically we have to handle:
```dart
    String simulateBugCalledTwice(String text) {
      String output1 = formatEditUpdate(text, removeLast(text));
      String output2 = formatEditUpdate(output1, removeLast(text));
      return output2;
    }

    String simulateBugCalledFourTimes(String text) {
      String output1 = formatEditUpdate(text, removeLast(text));
      String output2 = formatEditUpdate(output1, removeLast(text));
      String output3 = formatEditUpdate(output2, output1);
      String output4 = formatEditUpdate(output3, output2);
      return output4;
    }
```
I'll add tests for these conditions, both for the normal erase character (where formatEditUpdate gets called only once), as well as accounting for the framework bug which happens on my device. Then we can try to figure out some hack that returns correctly despite the framework bug :)

**Comment by luistrivelatto** [comment]
I think I've found a way to handle the extra formatEditUpdate calls, along with the normal case. Unfortunately, a side effect is that it loses the ability to insert/erase in the middle or paste text into the TextField. This is because, without assuming the user is inserting/removing characters in the end, it's actually ambiguous to know if 2 subsequent calls to formatEditUpdate are due to the Flutter bug, or due to the user pasting text or inserting/erasing in the middle.

The fix is based on the observation that, among the extra formatEditUpdate calls, only the first is actually consistent with a removal in the end. For example, take the second call above:
```
formatEditUpdate (oldValue: "12.345,67 €", newValue: "123.456,78")
```
This `newValue` can't be obtained by adding/removing one character from the end of `oldValue`. So we can use this insertion/removal consistency to detect if the `formatEditUpdate` call is being triggered by a user change, or if it's an extra framework call. And if it's an extra framework call, we return the `oldValue`, and that seems to work (passes all tests).

I'm submitting a PR with this fix, but I understand that accepting or not the PR is a decision to take (because of the lost functionality vs fixing a bug which, who knows, might be pretty rare, or might be fairly common). So feel free to choose whichever you find the best :)
