### ISSUE TITLE
How to Disable Locale

### ISSUE THREAD

**Issue by echomartha** [gtgalone/currency_text_input_formatter#16]
i want this `IDR` not showing , its that possible ?

 ![image](https://user-images.githubusercontent.com/71472725/111765497-5fb95c80-88df-11eb-8fb6-4e8c35b8718d.png)

**Comment by gtgalone** [comment]
@echomartha 
Thank you for using!

That is the symbol.

You can remove with passing argument `symbol: ''`.

**Comment by echomartha** [comment]
@gtgalone  okay thanks for your response :)
