### ISSUE TITLE
Start value

### ISSUE THREAD

**Issue by netgfx** [gtgalone/currency_text_input_formatter#18]
hello, I have

```
TextFormField(
    inputFormatters: [CurrencyTextInputFormatter(locale: "en_US", decimalDigits: 2, symbol: "")],
    keyboardType: TextInputType.numberWithOptions(decimal: true)
    );
```
and when I type `1` it goes to `0.01` is there a way to start from `1` and only if I press `,` to add a decimal? It feels very unnatural to start from 0.01 cent

**Comment by gtgalone** [comment]
@netgfx Thank you for using.

This library supports only right start, because of currency.

You should  use`RegExp` instead.
