### ISSUE TITLE
Make the decimal points optional

### ISSUE THREAD

**Issue by Sun3** [gtgalone/currency_text_input_formatter#2]
I would be great if the decimal points are optional and the format not shown if the user does not tap the period (.) to enter the decimal points.

```
1,250
```

if user enters ```.99``` then show decimal format
```
1,250.99
```

Thank you

**Comment by gtgalone** [comment]
@Sun3 Thank you for feature request. I will figure it out. :)

**Comment by Sun3** [comment]
That's awesome, thank you.

**Comment by Sun3** [comment]
Hi, I was just checking if this feature is possible.

Thank you.

**Comment by gtgalone** [comment]
Hello, Sun.

For now, It is not possible.

There is optional decimal but you want it would be automatic decimal.

I think some people can be confused about it and It has to be used for
global currency.

But I will figure it out in a better way. Thank you :)

**Comment by Sun3** [comment]
Thank you, I appreciate it.

**Comment by Sun3** [comment]
ps: I thought that one way to avoid confusion is to have an optional flag to allow optional decimal or the number of decimal places.

Thanks,
Marco

**Comment by gtgalone** [comment]
@Sun3 Thank you Marco. For now, There is option for number for decimal.

```
CurrencyTextInputFormatter(
   locale: 'ko',
   decimalDigits: 0,
   symbol: 'KRW(원) ',
)
```

But this case cannot use any decimal, You need to turn off / on strict decimal right?

For you, How about using FilteringInputFormatter with RegExp?

```
FilteringTextInputFormatter.allow(RegExp(r'^\d*\.?\d*$'))
```

It can be helpful for you :)

**Comment by Sun3** [comment]
Thanks for the help.
