### ISSUE TITLE
Prevent cursor from moving to the end of string

### ISSUE THREAD

**Issue by alryan-dev** [gtgalone/currency_text_input_formatter#25]
If the user wants to remove a digit in the middle to replace it to something else (ex. 1,000.00 to 1,500.00), the cursor moves to the end which is for me not a good user experience. I end up retyping the whole amount. Is there an existing way to prevent this behavior?

**Comment by gtgalone** [comment]
@alryan-dev Thank you for using!

I will figure it out.

If you have an idea, Feel free to contribute.

**Comment by gtgalone** [comment]
@alryan-dev

Because it is rtl, It is unable to change in the middle of value.

and I will add direction property ltr for flexible.

In this direction users will be able to change in the middle of value.

**Comment by carloscasanovad** [comment]
This issue was solved? I'm having the same problem as @alryan-dev

**Comment by vidhi002** [comment]
any update on this? facing same issue.

**Comment by jonsaw** [comment]
I managed to got it to work. Will try to clean things up to create a PR

https://github.com/user-attachments/assets/3d85e4db-c75c-4d9d-a868-5d0201a1fc0a
