### ISSUE TITLE
negative amount

### ISSUE THREAD

**Issue by kgabol** [gtgalone/currency_text_input_formatter#26]
getUnformattedValue does not return negative amount when negative amount was entered.

**Comment by gtgalone** [comment]
@kgabol Thank you for reporting this issue!

I have just published with fixing this issue.

Please use new release 2.1.4!

Thank you again :)

**Comment by jahoefne** [comment]
@gtgalone 

The fix seems to have broken a use case that worked for me before.
I used the .format Method to format Currency-Values for display-purposes. 

before the change .format("-2000") => "-200.00€" now "200.00€"

**Comment by gtgalone** [comment]
@jahoefne Thank you for your comment.

I have just published with it.

So please use 2.1.5 :)
