### ISSUE TITLE
locale CLP

### ISSUE THREAD

**Issue by smunozjara** [gtgalone/currency_text_input_formatter#27]
El paquete no funciona cuando asigno el parametro locale como CLP (peso chileno)

**Comment by gtgalone** [comment]
@smunozjara Sorry I can not read your language.

Please rewrite in English Thank you :)

**Comment by smunozjara** [comment]
The package does not work when I assign the locale parameter as CLP (Chilean peso)

**Comment by gtgalone** [comment]
@smunozjara

maybe you should make this issue to intl package, because we are using this package for locale

https://github.com/dart-lang/intl

I will close it.

Thank you!
