### ISSUE TITLE
Working with decimal points is atypical 

### ISSUE THREAD

**Issue by 0xPixelfrost** [gtgalone/currency_text_input_formatter#28]
Hi,

i think the way how you work with decimal points in your library is a bit confusing and I try to explain this by a small sample: 

_How it is:_
Entered value for 100 + click on decimal separator + 99 results in: 10,000.99

_How it should be_:
Entered value for 100 + click on decimal separator + 99 results in: 100.99

Your formatter seems always to add new values to the decimal points and shift the main number to the left instead. This behaviour is compared to normal calculators very atypical and hard to maintain is you want to correct a number input.

Tested on 2.1.5

**Comment by gtgalone** [comment]
@0xPixelfrost Thank you so much!

If you have any idea. Feel free to contribute.

**Comment by john182** [comment]
locale BR not working, decimal Separator is space

![image](https://user-images.githubusercontent.com/10438644/156835814-f11d4135-107f-44ad-a680-8d352093bffb.png)


![image](https://user-images.githubusercontent.com/10438644/156836045-4efab865-93ec-49c9-8a5b-5e22a52a66dd.png)

**Comment by gtgalone** [comment]
@john182 Thank you for the issue.

I will check it this weekend.

**Comment by gtgalone** [comment]
@john182 
Could you share your code?

for me it is working.

<img width="674" alt="Screen Shot 2022-06-17 at 1 54 42 PM" src="https://user-images.githubusercontent.com/23162037/174400002-a2cef9b7-02d6-443c-8d4a-4d10bd54221d.png">

**Comment by gtgalone** [comment]
@0xPixelfrost current version direction is only rtl. so cursor will change to right end.

I will add direction property ltr. it might be worked what you want.

**Comment by han-tm** [comment]
Someone solved this problem? I need the pennies to be entered last
