### ISSUE TITLE
Add Trailing Symbol

### ISSUE THREAD

**Issue by Tichz** [gtgalone/currency_text_input_formatter#29]
I haven't found a way to add a trailing symbol I'm missing something or there's really no way to add a trailing symbol

**Comment by gtgalone** [comment]
@Tichz Thank you for using!

You should change locale for trailing symbol now. 
EUR has trailing symbol.

If you want to set custom symbol position, feel free to contribute :)

**Comment by Tichz** [comment]
@gtgalone 
thanks for the help you have no idea how it helped me
