### ISSUE TITLE
Unable to type '-' for a negative amount.

### ISSUE THREAD

**Issue by holtalanm** [gtgalone/currency_text_input_formatter#3]

**Comment by gtgalone** [comment]
@holtalanm Thank you for using. 

Yes.

You cannot use negative and You should use prefix at input decoration for negative.

**Comment by holtalanm** [comment]
that....is not the same thing at all.

**Comment by gtgalone** [comment]
In prefix, You can add dropdown for positive and negative at this time.

I will figure it out :)

**Comment by gtgalone** [comment]
@holtalanm Thank you. I just have published 0.2.0  :)
