### ISSUE TITLE
after delete all number in a text form field, then remains "0" / zero

### ISSUE THREAD

**Issue by wiztensai** [gtgalone/currency_text_input_formatter#31]
hi!

i have a problem, when after delete all number in a text form field, then remains "0"
then i enter number 1, it become "01". (1 behind 0)

how to directly replace 0 to 1?

thanks

**Comment by gtgalone** [comment]
@wiztensai Thank you for using!

Could you provide your code?

If I delete all number, value is null for me.

**Comment by gtgalone** [comment]
I will close it. we can reopen it.
