### ISSUE TITLE
Symbol appears when initialValue is set

### ISSUE THREAD

**Issue by agharium** [gtgalone/currency_text_input_formatter#32]
```
FormBuilderTextField(
  name: 'value',
  decoration: const InputDecoration(
    labelText: 'Valor'
  ),
  inputFormatters: [
    CurrencyTextInputFormatter(
      locale: 'pt-br',
      decimalDigits: 2,
      symbol: '',
    ),
  ],
  keyboardType: TextInputType.number,
  onChanged: (value) => log(value!.replaceAll('.', '').replaceAll(',', '.')),
  initialValue: action == 'edit' ? _formatter.format(vm.movement.value.toString()) : '',
),
```

I set symbol as an empty string, and it renders like this:

![image](https://user-images.githubusercontent.com/28984633/174161484-303ed03a-1b1c-4066-a724-b2e558b7ba40.png)

But when initialValue is set, the symbol appears anyway:

![image](https://user-images.githubusercontent.com/28984633/174161646-faf7f2f5-48ad-4bcc-939c-71531347ff82.png)

Can someone help me? 😁🙏

thanks!

**Comment by gtgalone** [comment]
@agharium Thank you for reporting the issue!

I will figure it out soon.

**Comment by gtgalone** [comment]
@agharium 
your code will be changed to
```
final CurrencyTextInputFormatter _formatter = CurrencyTextInputFormatter(
    locale: 'pt-br',
    decimalDigits: 2,
    symbol: '',
);

TextFormField(
    inputFormatters: [_formatter],
    initialValue: _formatter.format('2000'),
),
```
