### ISSUE TITLE
Update for flutter 3.0

### ISSUE THREAD

**Issue by parmeetmaster** [gtgalone/currency_text_input_formatter#33]
Its not working flutter 3.0 version pls update

**Comment by gtgalone** [comment]
@parmeetmaster Thank you for reporting the issue!

I will update it soon!

**Comment by gtgalone** [comment]
@parmeetmaster 
I have tested with My version. it is working.
```
Flutter 3.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision fb57da5f94 (4 weeks ago) • 2022-05-19 15:50:29 -0700
Engine • revision caaafc5604
Tools • Dart 2.17.1 • DevTools 2.12.2
```

Could you provide error message and your flutter version?

**Comment by gtgalone** [comment]
I will close it for now.
