### ISSUE TITLE
formatter value reset to `initialValue` after the the next following step using `Stepper`

### ISSUE THREAD

**Issue by jmarrr** [gtgalone/currency_text_input_formatter#37]
Hi, Whenever I go to the next step after I inputted the value on the `TextFormField` the `formatter.getUnformattedValue().toInt()` returns the expected value however when I go to the next step the `formatter` value resets back to the `intialValue` it doesn't keep the input value. How do I keep the value on `Stepper`? 

Example snippet
https://pastebin.com/ULWBxnpD

**Comment by gtgalone** [comment]
Hello @jmarrr !

Of course. If you want your state to persist, Could you check it out?

https://stackoverflow.com/questions/63460629/flutter-get-data-from-stepper-textfields
