### ISSUE TITLE
Cursor selection is not at the position where the number is being changes but behind the currency abbreviation

### ISSUE THREAD

**Issue by bennidietz** [gtgalone/currency_text_input_formatter#39]
The cursor selection is always behind the currency abbreviation, however the user might expect it to be right before it as the text changes there.

**Comment by gtgalone** [comment]
Hello @bennidietz !

That is expected action.

For now it only supports right to left direction.

But I am going to add left to right direction.

after this, it would be more flexible!

**Comment by gtgalone** [comment]
Additional, Could you let me know the locale that you are using?

**Comment by bennidietz** [comment]
Hi @gtgalone,
alright. I'm using the German and English locale.
