### ISSUE TITLE
Cannot parse text to num in TextEditingController

### ISSUE THREAD

**Issue by Lazizbek97** [gtgalone/currency_text_input_formatter#42]
I have added the formatter to textformfield, but when i try to parse the controller.text, it fails.
reason: I cannot remove empty space inside numbers. 
What is the problem? How can i remove empty spaces and parse it to number?

**Comment by gtgalone** [comment]
Hello @Lazizbek97 

Maybe you can use built-in methods.

https://github.com/gtgalone/currency_text_input_formatter#with-built-in-methods
