### ISSUE TITLE
IS THERE A WAY TO REMOVE CURRENCY FROM OUTPUT?

### ISSUE THREAD

**Issue by Devlonoah** [gtgalone/currency_text_input_formatter#45]
When used with textfield ,the output I get is something like this:
`USD20,000`.

Is there a way to get a formatted currency without the currency, like this:

`20,000`.

?

**Comment by gtgalone** [comment]
Hello @Devlonoah !

You can use built-in method.

Check this out.

https://github.com/gtgalone/currency_text_input_formatter#with-built-in-methods

```
// Built-in Methods
print(formatter.getFormattedValue()); // $ 2,000
print(formatter.getUnformattedValue()); // 2000.00
print(formatter.format('2000')); // $ 2,000
```

**Comment by Devlonoah** [comment]
thanks.
