### ISSUE TITLE
Manual input dot (.) for decimal number

### ISSUE THREAD

**Issue by vickygaugau** [gtgalone/currency_text_input_formatter#46]
Hi, 
Thanks for your library.
I have an issue.
I want to manual input the dot (.) for decimal number
But if i set decimalDigits: 0, i cannot input the dot (.)
If i set decimalDigits: 2, it is auto input dot (.) when i input the first number
ex: 1 -> 0.01
--- my setting currency for the indian currency ---
CurrencyTextInputFormatter(
          symbol: '',
          decimalDigits: 0,
          locale: 'en_IN',
        )
---
Thanks for your supporting.

https://user-images.githubusercontent.com/4328044/236773571-9c4e6a33-7fa7-432e-9142-566661ff0a2f.mov

**Comment by gtgalone** [comment]
Hi @vickygaugau !

Currently we only support right-left direction.

So if you want to add 1, entering  0 0 1 will show you 1.00.

Thanks!

**Comment by MrLightful** [comment]
@gtgalone do you accept feature requests for that? Coz technically I get why this way is more accurate, but in terms of user experience, many of my users are highly annoyed by it.

**Comment by sinanhaci** [comment]
I'm experiencing the same issue, I think this should be a choice.

**Comment by BobFactory** [comment]
+1 for the same feature request. Its very natural for the user to manually select when to enter the decimal number, without that I personally cannot use this for my project.
