### ISSUE TITLE
Issue on format with CurrencyTextInputFormatter

### ISSUE THREAD

**Issue by atsen-dev** [gtgalone/currency_text_input_formatter#49]
Hi,

I just want to share an issue than annoy me with _CurrencyTextInputFormatter_ is that if I want to format that value : 20.0 , It will format as 2.00 for example.

In my case I want to init an input with 131.0 (double value) as value and that is my output using formatter : 
![image](https://github.com/gtgalone/currency_text_input_formatter/assets/32575538/6928fa37-ab95-46fe-9caa-6901db30b274)

Did you know that issue ?

**Comment by atsen-dev** [comment]
The issue come from this part of the plugin (line 95) : 
![image](https://github.com/gtgalone/currency_text_input_formatter/assets/32575538/7f6820a1-8209-4875-a2e0-fa63f4936a4e)

EDIT : 

As you can see input is 131 but after line 95, _newNum is 1.31


The only workaround I found is to format every value with thr right precision like this : 
![image](https://github.com/gtgalone/currency_text_input_formatter/assets/32575538/d1fe396d-0bdd-4c4c-af83-e1b01733c818)

I thinks It would be great If we can improve that to be able to set a double value without the need of the workaround

**Comment by pedrolemoz** [comment]
I had the same issue as you. Instead of using `.format` method, use `.formatDouble`.
