### ISSUE TITLE
How to get the current value of the textfield without mask

### ISSUE THREAD

**Issue by marcos930807** [gtgalone/currency_text_input_formatter#5]
Hi @gtgalone 
Is there a simple way to obtain the value of textfield without the mask? If a regular expression is necessary, you could provide it in the documentation, thanks.

Edit:
Reading the code from the lib with this regular expression replaceAll (RegExp ('[^ 0-9]'), '') I can get the numeric value but without taking into account the decimals, it would be great if the textInputFormatter had a getter that give the double value with decimals that the textField has

**Comment by gtgalone** [comment]
@marcos930807 Sorry for late reply :)

You can get the value of textfield. There are several ways.

1. TextEditingContoller - https://api.flutter.dev/flutter/widgets/TextEditingController-class.html

2. onChange event with setState.

**Comment by marcos930807** [comment]
Hi, I mean get de value WITHOUT the mask.😉

**Comment by gtgalone** [comment]
@marcos930807 Oh I got it :)

You can just use replace with string value.

**Comment by bartekpacia** [comment]
I think there should be some better solution for this problem, because there are many locales and manually writing replacing `,` and `.` and e.g `USD` at the end is very error-prone.

**Comment by gtgalone** [comment]
@bartekpacia @marcos930807 Oh I am so sorry.

I forgot to add updated to readme.

please check it. https://github.com/gtgalone/currency_text_input_formatter/blob/master/CHANGELOG.md#210

I have added to some methods for this.

**Comment by bartekpacia** [comment]
I'll share how I solved it (before I knew about `getFormattedValue` and `getUnformattedValue`):

```dart
@override
Widget build(BuildContext context) {
  // keep these 2 in sync
  final currencyFormat = NumberFormat.currency(
    locale: context.locale.toLanguageTag(),
    symbol: 'PLN', // Polish złoty
  );
  final currencyInputFormatter = CurrencyTextInputFormatter(
    locale: context.locale.toLanguageTag(),
    symbol: 'PLN',
  );

  double price = 21.37;

  // return Column(...);
}
```

and then 

```dart
TextFormField(
  initialValue: currencyFormat.format(price),
  onChanged: (newText) {
    final cleaned = newText.replaceAll('PLN', '').trim();
    double? newPrice;
    try {
      newPrice = currencyFormat.parse(cleaned).toDouble();
    } catch (err) {
      // it's okay for price to be null
    }
  
   // update the price to my cubit
    context.read<SomeCubit>().setPrice(newPrice);
  },
  keyboardType: TextInputType.number,
  inputFormatters: [currencyInputFormatter],
  decoration: InputDecoration(
    contentPadding: const EdgeInsets.symmetric(
      horizontal: 12,
    ),
    labelText: 'Price',
    border: const OutlineInputBorder(),
  ),
)
```

**Comment by bartekpacia** [comment]
@gtgalone thanks for the fast response:) I think you should update README to include `getFormattedValue` and `getUnformattedValue` :)

**Comment by gtgalone** [comment]
@bartekpacia Sure. I will do it for this weekend.
