### ISSUE TITLE
How can I change the validator configuration at runtime?

### ISSUE THREAD

**Issue by MiniSuperDev** [gtgalone/currency_text_input_formatter#59]
For example when the user change the [locale](https://api.flutter.dev/flutter/widgets/WidgetsBindingObserver/didChangeLocales.html), or when you have a field that is a country, so the symbol and locale of the `CurrencyTextInputFormatter` will need to be updated.

Thanks

**Comment by gtgalone** [comment]
Hello @MiniSuperDev 

You can only change some value in runtime to use setState(() {}).
