### ISSUE TITLE
Cursor Behavior Issue with 'pt-BR' Locale in Formatter Configuration

### ISSUE THREAD

**Issue by Vitor1703** [gtgalone/currency_text_input_formatter#62]
When setting the locale to 'pt-BR' in the formatter configuration, the cursor moves unexpectedly. It doesn't stay at the end of the text as it should. Using the version 2.2.4

https://github.com/user-attachments/assets/248af5a2-0122-41a4-bac9-04c67724a0f4

**Comment by gtgalone** [comment]
Thanks @Vitor1703 

You should update the package to v2.2.5
