### ISSUE TITLE
Delete-Button doesn't work when currency symbol is at the end

### ISSUE THREAD

**Issue by nicomachtapps** [gtgalone/currency_text_input_formatter#7]
Hi, I like your package and would love to use it. Unfortunately it doesn't properly work at the moment, when the currency symbol is positioned at the end. For example in Germany the currency is formatted as '25.000,00 €', which is correct. But then the delete key doesn't work anymore.

**Comment by gtgalone** [comment]
@drbizeps Thank you for the issue. Let me check :)

**Comment by gtgalone** [comment]
@drbizeps Please use 0.3.0 version. I just have published after fixing this issue :)

**Comment by nicomachtapps** [comment]
Thank you so much for the quick response and fix. It works wonderfully now.
