### ISSUE TITLE
pattern bug, input cannot more than 9.99

### ISSUE THREAD

**Issue by RaisTMJ** [gtgalone/currency_text_input_formatter#8]

**Comment by RaisTMJ** [comment]
library only allow to write 3 digit such as us in image, it only allow value below 9.99. Pattern input bug
![pattern bug](https://user-images.githubusercontent.com/46097877/97463458-ba770980-197a-11eb-8888-70fce835cd78.jpg)

**Comment by gtgalone** [comment]
@RaisTMJ Can you share your code?

**Comment by RaisTMJ** [comment]
i retry to produce the code and it work well. I will close the issues
