### ISSUE TITLE
Formatter returns an extra space when formatting with some locales and with symbol = ''

### ISSUE THREAD

**Issue by luistrivelatto** [gtgalone/currency_text_input_formatter#9]
By creating the following formatter (I'm using locale = 'es', but this applies to other locales too):
```dart
var formatter = CurrencyTextInputFormatter(locale: 'es', symbol: '');
```
The formatter adds an extra space when formatting. That is, after typing "0", the above formatter returns "0,00 ". For some locales, such as pt_BR, the extra space can be in the front (i.e., " 0,00").

This is because NumberFormat.currency doesn't handle the symbol being empty, instead it expects either a null symbol (in which case it formats with the locale ISO code) or some non-empty string, in which case it would format as "0,00 €", in locale es, or "R$ 0,00", in locale pt_BR.

However, since Flutter's TextField includes `preffixText` and `suffixText` as decoration properties, I assume it's a fairly common case to use, for example, `preffixText = r'R$'`, and then show no symbol in the actual text field string. In that case, this extra space is counter-intuitive (and was bugging my parser haha).

I believe this fix is very simple, just requires adding a `trim()` on the string after formatting. I'm submitting a PR for it, along with some unit tests to validate the changes. Feel free to point any issues :)

**Comment by gtgalone** [comment]
@luistrivelatto 

Thank you so much!

Awesome for adding test code 👍.

I have just published new release 1.0.1 with your commit.
